/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import BeetSolana
import Solana


/**
* Arguments used to create {@link Sessiontoken}
* @category Accounts
* @category generated
*/
public protocol SessiontokenArgs {
    
     var authority: PublicKey { get }
     var targetProgram: PublicKey { get }
     var sessionSigner: PublicKey { get }
     var validUntil: Int64 { get }
}

/**
 * Holds the data for the {@link Sessiontoken} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
public struct Sessiontoken: SessiontokenArgs {
  

  public let authority: PublicKey
  public let targetProgram: PublicKey
  public let sessionSigner: PublicKey
  public let validUntil: Int64

  /**
   * Creates a {@link Sessiontoken} instance from the provided args.
   */
  public static func fromArgs(args: Args) -> Sessiontoken {
    return Sessiontoken(
        authority: args["authority"] as! PublicKey,
        targetProgram: args["targetProgram"] as! PublicKey,
        sessionSigner: args["sessionSigner"] as! PublicKey,
        validUntil: args["validUntil"] as! Int64
    )
  }
  /**
   * Deserializes the {@link Sessiontoken} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func fromAccountInfo(
    accountInfo: Foundation.Data,
    offset:Int=0
  ) -> ( Sessiontoken, Int )  {
    return Sessiontoken.deserialize(buf: accountInfo, offset: offset)
  }
  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Sessiontoken} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  public static func fromAccountAddress(
    connection: Api,
    address: PublicKey,
    onComplete: @escaping (Result<Sessiontoken, Error>) -> Void
  ) {
    connection.getAccountInfo(account: address.base58EncodedString) { result in
        switch result {
            case .success(let pureData):
                if let data = pureData.data?.value {
                    onComplete(.success(Sessiontoken.deserialize(buf: data).0))
                } else {
                    onComplete(.failure(SolanaError.nullValue))
                }
            case .failure(let error):
                onComplete(.failure(error))
        }
    }
  }
  /**
   * Deserializes the {@link Sessiontoken} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func deserialize(
    buf: Foundation.Data,
    offset: Int = 0
  ) -> ( Sessiontoken, Int ) {
    return sessionTokenBeet.deserialize(buffer: buf, offset: offset)
  }
  /**
   * Serializes the {@link Sessiontoken} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  public func serialize() -> ( Foundation.Data, Int ) {
    return sessionTokenBeet.serialize(instance: Sessiontoken(authority : self.authority,
        targetProgram : self.targetProgram,
        sessionSigner : self.sessionSigner,
        validUntil : self.validUntil))
  }
    /**
  * Returns the byteSize of a {@link Buffer} holding the serialized data of
  * {@link Sessiontoken}
  */
  static func byteSize() -> UInt {
      return sessionTokenBeet.byteSize
  }
  /**
  * Fetches the minimum balance needed to exempt an account holding
  * {@link Sessiontoken} data from rent
  *
  * @param connection used to retrieve the rent exemption information
  */
  static func getMinimumBalanceForRentExemption(
      connection: Api,
      commitment: Commitment?,
      onComplete: @escaping(Result<UInt64, Error>) -> Void
  ) {
      return connection.getMinimumBalanceForRentExemption(dataLength: UInt64(Sessiontoken.byteSize()), commitment: commitment, onComplete: onComplete)
  }
  /**
  * Determines if the provided {@link Buffer} has the correct byte size to
  * hold {@link Sessiontoken} data.
  */
  static func hasCorrectByteSize(buf: Foundation.Data, offset:Int=0) -> Bool {
      return buf.bytes.count - offset == Sessiontoken.byteSize()
  }
}
  /**
   * @category Accounts
   * @category generated
   */
  public let sessionTokenBeet = BeetStruct(
    fields:[
        
        ("authority", (.init(value: .scalar(BeetPublicKey())))),
        ("targetProgram", (.init(value: .scalar(BeetPublicKey())))),
        ("sessionSigner", (.init(value: .scalar(BeetPublicKey())))),
        ("validUntil", (.init(value: .scalar(i64()))))
    ],
    construct: Sessiontoken.fromArgs,
    description: "Sessiontoken"
)
